Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  config.vm.provision "shell", path: "setup.sh"

  # Reboot to ensure we're using the most recent kernel
  config.vm.provision :reload
end
