---

- name: Install EPEL
  yum: name={{ item }} state=present
  with_items:
    - epel-release

- name: Install Dependencies
  yum: name={{ item }} state=present
  with_items:
    - git
    - ansible
    - vim
    - nano 
    - wget
    - MySQL-python
    
- name: Download Semaphore
  get_url:
    url: https://github.com/ansible-semaphore/semaphore/releases/download/v2.0.2/semaphore_linux_amd64
    dest: /usr/bin/semaphore
    mode: 0755

- name: Install Percona Repo
  yum: 
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
    state: present

- name: Install Percona Server
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - Percona-Server-client-56
    - Percona-Server-devel-56
    - Percona-Server-server-56
    - Percona-Server-shared-56

- name: Start the MySQL Service
  service: name=mysql state=started enabled=yes

- name: Create Semaphore DB User
  mysql_user: 
    name: semaphore
    password: 'semaphore'
    update_password: always
    priv: semaphore.*:ALL
